/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package election;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class EspaceVote extends javax.swing.JFrame {

    Connection Con = null;
    PreparedStatement pst  = null;
    ResultSet Rs=null;
    Statement St = null;
    public EspaceVote() {
        initComponents();
        tbload();
    }
    int VotingID;
    public EspaceVote(int eid){
       initComponents();
        tbload();
       VotingID=eid;
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        deconnect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonSeconnecter1 = new swing.ButtonSeconnecter();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Election de Classe");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 8, -1, -1));

        deconnect.setBackground(new java.awt.Color(242, 204, 255));
        deconnect.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\IMAGES\\icons8.png")); // NOI18N
        deconnect.setBorder(null);
        deconnect.setBorderPainted(false);
        deconnect.setContentAreaFilled(false);
        deconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnectActionPerformed(evt);
            }
        });
        jPanel2.add(deconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 710, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\IMAGES\\icons8-nom-100.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 90));

        buttonSeconnecter1.setText("Voter");
        buttonSeconnecter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSeconnecter1MouseClicked(evt);
            }
        });
        jPanel2.add(buttonSeconnecter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 150, 30));

        jLabel3.setText("Nom et Prenom");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel4.setText("Age");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel5.setText("Genre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        User.setBackground(new java.awt.Color(153, 255, 153));
        User.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        User.setText("Userconnected");
        jPanel2.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\IMAGES\\icons8-compte-test-30 (1).png")); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Online");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 190, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setUser(String name){
        User.setText(name);
    }
    private void deconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnectActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir vous déconnecter ?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            // Fermez la fenêtre uniquement si l'utilisateur clique sur "Oui"
            dispose();
        }
    }//GEN-LAST:event_deconnectActionPerformed

    String Key = "";
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         int MyIndex = jTable1.getSelectedRow();
        if (MyIndex != -1) {
        Key = model.getValueAt(MyIndex, 0).toString(); 
        String candidateID = model.getValueAt(MyIndex, 0).toString();
        jLabel8.setText(model.getValueAt(MyIndex, 1).toString());
        jLabel9.setText(model.getValueAt(MyIndex, 2).toString());
        jLabel10.setText(model.getValueAt(MyIndex,3).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked
    }
    int Vid;
    ResultSet Rs1 =null;
    Statement St1 = null;
    private void VoteCount(){
      try{
        St1 = Con.createStatement();
        Rs1 = St1.executeQuery("select Max(voteid) from votetb");
        Rs1.next();
        Vid = Rs1.getInt(1)+1;
      }catch(Exception ex){
      
      }
    }

    private void buttonSeconnecter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSeconnecter1MouseClicked
       if (Key.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Select votre Candidat");
    } else {
        try {
            int voteCount = getVoteCount(VotingID);

            if (voteCount > 0) {
                JOptionPane.showMessageDialog(this, "Vous avez déjà voté. Vous ne pouvez pas voter plusieurs fois.");
                return;
            }

            VoteCount();
            Con = DriverManager.getConnection("jdbc:MySQL://localhost:3306/election", "root", "");
            PreparedStatement Add = Con.prepareStatement("insert into votetb VALUES (?, ?, ?)");

            Add.setInt(1, Vid);
            Add.setInt(2, VotingID);
            Add.setInt(3, Integer.parseInt(Key));

            int rowsAffected = Add.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Vote réalisé");
            } else {
                JOptionPane.showMessageDialog(this, "Un problème de vote");
            }

            // Close the resources
            Add.close();
            Con.close();
            tbload();
            buttonSeconnecter1.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_buttonSeconnecter1MouseClicked
    }
    private int getVoteCount(int voterID) {
    try {
        Con = DriverManager.getConnection("jdbc:MySQL://localhost:3306/election", "root", "");
        PreparedStatement checkVote = Con.prepareStatement("SELECT count(*) FROM votetb WHERE electeurid = ?");
        checkVote.setInt(1, voterID);
        ResultSet rs = checkVote.executeQuery();
        rs.next();
        return rs.getInt(1); // Return the count of votes
    } catch (Exception e) {
        e.printStackTrace();
        return -1; // Return -1 to indicate an error
    }
    }



    public void tbload(){
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/election", "root", "");
        St = Con.createStatement();

        Rs = St.executeQuery("SELECT * FROM candidat");

        // Create column names
        Vector<String> columnNames = new Vector<>();
        columnNames.add("ID");
        columnNames.add("Nom");
        columnNames.add("Age");
        columnNames.add("Genre");

        // Create data for the table model
        Vector<Vector<Object>> data = new Vector<>();

        // Populate data from the ResultSet
        while (Rs.next()) {
            Vector<Object> rowData = new Vector<>();
            rowData.add(Rs.getString("cid"));
            rowData.add(Rs.getString("cnom"));
            rowData.add(Rs.getInt("cage"));
            rowData.add(Rs.getString("cgenre"));

            data.add(rowData);
        }

        // Create the table model with column names and data
        DefaultTableModel model = new DefaultTableModel(data, columnNames);

        // Set the model to the JTable
        jTable1.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspaceVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspaceVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspaceVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaceVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspaceVote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel User;
    private swing.ButtonSeconnecter buttonSeconnecter1;
    private javax.swing.JButton deconnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
